stages:
  - static_analysis
  - test
  - test_edge
  - publish

image: registry.gitlab.com/gui-don/moustache-ci-docker:7.4

cache:
  paths:
    - vendor/

variables:
  SYMFONY_ENV: 'test'

include:
  - project: 'gitlab-org/gitlab'
    ref: master
    file: '/lib/gitlab/ci/templates/Security/Dependency-Scanning.gitlab-ci.yml'

# Static analysis

.sa_template:
  stage: static_analysis
  before_script:
    - composer install -o --no-interaction

code_style:
  extends: .sa_template
  script:
    - vendor/bin/php-cs-fixer fix --allow-risky yes --dry-run .

sast:
  extends: .sa_template
  artifacts:
    reports:
      sast: gl-sast-report.json
  script:
    - chmod +x ./vendor/pheromone/phpcs-security-audit/symlink.sh
    - vendor/pheromone/phpcs-security-audit/symlink.sh
    - vendor/bin/phpcs --error-severity=1 --warning-severity=6 --report=json --report-file=gl-sast-report.json --standard=./vendor/pheromone/phpcs-security-audit/example_base_ruleset.xml --extensions=php,inc,lib,module,info src

composer:
  extends: .sa_template
  script:
    - composer validate

stan:
  extends: .sa_template
  script:
    - vendor/bin/phpstan analyse src --level 6

# Unit Tests

.unit_template:
  stage: test
  script:
    - vendor/bin/phpunit
  before_script:
    - composer install -o --no-interaction

unit:7.2:
  extends: .unit_template
  image: registry.gitlab.com/gui-don/moustache-ci-docker:7.2

unit:7.3:
  extends: .unit_template
  image: registry.gitlab.com/gui-don/moustache-ci-docker:7.3

unit:7.4:
  extends: .unit_template
  image: registry.gitlab.com/gui-don/moustache-ci-docker:7.4

unit:rc:
  extends: .unit_template
  stage: test_edge
  image: registry.gitlab.com/gui-don/moustache-ci-docker:rc
  allow_failure: true
  only:
    variables:
      - $SCHEDULE == "edge"

unit:coverage:
  stage: test
  image: registry.gitlab.com/gui-don/moustache-ci-docker:coverage
  allow_failure: true
  script: vendor/bin/phpunit --coverage-text --coverage-html build/coverage-report --colors=never
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    paths:
      - coverage

# Publish

publish<:
  stage: publish
  script:
    - scripts/create_phar.php
  artifacts:
    paths:
      - rico-lib.phar
#  only:     
#    - tags
#    - /^v?[0-9]+\.[0-9]+\.[0-9]+$/
#  except:     
#    - branches

